name: Build and Package SharpTimer

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (Debug/Release)'
        required: true
        default: 'Debug'
        type: choice
        options:
        - Debug
        - Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SharpTimer-main.sln

    - name: Build SharpTimerAPI
      run: dotnet build SharpTimerAPI/SharpTimerAPI.csproj --configuration ${{ matrix.build_type }} --no-restore --verbosity normal
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Build SharpTimer Plugin
      run: dotnet build src/SharpTimer.csproj --configuration ${{ matrix.build_type }} --no-restore --verbosity normal
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Build SharpTimer-Example
      run: dotnet build SharpTimerAPI-Example/SharpTimer-Example.csproj --configuration ${{ matrix.build_type }} --no-restore --verbosity normal
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Create build info
      run: |
        echo "Build Date: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > build_info.txt
        echo "Build Type: ${{ matrix.build_type }}" >> build_info.txt
        echo "Git Commit: ${{ github.sha }}" >> build_info.txt
        echo "Git Ref: ${{ github.ref }}" >> build_info.txt
        echo "Repository: ${{ github.repository }}" >> build_info.txt

    - name: Package SharpTimerAPI
      run: |
        mkdir -p artifacts/SharpTimerAPI-${{ matrix.build_type }}
        cp -r Build/shared/SharpTimerAPI/* artifacts/SharpTimerAPI-${{ matrix.build_type }}/
        cp build_info.txt artifacts/SharpTimerAPI-${{ matrix.build_type }}/
        cd artifacts
        tar -czf SharpTimerAPI-${{ matrix.build_type }}.tar.gz SharpTimerAPI-${{ matrix.build_type }}/
        zip -r SharpTimerAPI-${{ matrix.build_type }}.zip SharpTimerAPI-${{ matrix.build_type }}/

    - name: Package SharpTimer Plugin
      run: |
        mkdir -p artifacts/SharpTimer-Plugin-${{ matrix.build_type }}
        cp -r Build/plugins/SharpTimer/* artifacts/SharpTimer-Plugin-${{ matrix.build_type }}/
        cp build_info.txt artifacts/SharpTimer-Plugin-${{ matrix.build_type }}/
        cd artifacts
        tar -czf SharpTimer-Plugin-${{ matrix.build_type }}.tar.gz SharpTimer-Plugin-${{ matrix.build_type }}/
        zip -r SharpTimer-Plugin-${{ matrix.build_type }}.zip SharpTimer-Plugin-${{ matrix.build_type }}/

    - name: Package SharpTimer-Example
      run: |
        mkdir -p artifacts/SharpTimer-Example-${{ matrix.build_type }}
        cp -r SharpTimerAPI-Example/bin/${{ matrix.build_type }}/net8.0/* artifacts/SharpTimer-Example-${{ matrix.build_type }}/
        cp build_info.txt artifacts/SharpTimer-Example-${{ matrix.build_type }}/
        cd artifacts
        tar -czf SharpTimer-Example-${{ matrix.build_type }}.tar.gz SharpTimer-Example-${{ matrix.build_type }}/
        zip -r SharpTimer-Example-${{ matrix.build_type }}.zip SharpTimer-Example-${{ matrix.build_type }}/

    - name: Upload SharpTimerAPI artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SharpTimerAPI-${{ matrix.build_type }}
        path: |
          artifacts/SharpTimerAPI-${{ matrix.build_type }}.tar.gz
          artifacts/SharpTimerAPI-${{ matrix.build_type }}.zip
        retention-days: 30

    - name: Upload SharpTimer Plugin artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SharpTimer-Plugin-${{ matrix.build_type }}
        path: |
          artifacts/SharpTimer-Plugin-${{ matrix.build_type }}.tar.gz
          artifacts/SharpTimer-Plugin-${{ matrix.build_type }}.zip
        retention-days: 30

    - name: Upload SharpTimer-Example artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SharpTimer-Example-${{ matrix.build_type }}
        path: |
          artifacts/SharpTimer-Example-${{ matrix.build_type }}.tar.gz
          artifacts/SharpTimer-Example-${{ matrix.build_type }}.zip
        retention-days: 30

    - name: Build Summary
      run: |
        echo "## Build Summary for ${{ matrix.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- **SharpTimerAPI**: Built and packaged" >> $GITHUB_STEP_SUMMARY
        echo "- **SharpTimer Plugin**: Built and packaged" >> $GITHUB_STEP_SUMMARY
        echo "- **SharpTimer-Example**: Built and packaged" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Type**: ${{ matrix.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Git Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Available Downloads:" >> $GITHUB_STEP_SUMMARY
        echo "- SharpTimerAPI-${{ matrix.build_type }}.tar.gz" >> $GITHUB_STEP_SUMMARY
        echo "- SharpTimerAPI-${{ matrix.build_type }}.zip" >> $GITHUB_STEP_SUMMARY
        echo "- SharpTimer-Plugin-${{ matrix.build_type }}.tar.gz" >> $GITHUB_STEP_SUMMARY
        echo "- SharpTimer-Plugin-${{ matrix.build_type }}.zip" >> $GITHUB_STEP_SUMMARY
        echo "- SharpTimer-Example-${{ matrix.build_type }}.tar.gz" >> $GITHUB_STEP_SUMMARY
        echo "- SharpTimer-Example-${{ matrix.build_type }}.zip" >> $GITHUB_STEP_SUMMARY 